var mainGame = new GameInterface();
mainGame.startGame();
mainGame.createPiece(1);
mainGame.executeDropPiece();
mainGame.executeRotatePiece(0);
mainGame.executeRotatePiece(0);
mainGame.executeDropPiece();
mainGame.executeDropPiece();
mainGame.executeDropPiece();
mainGame.createPiece(0);
mainGame.executeDropPiece();
mainGame.executeDropPiece();